
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: chashier
      POSTGRES_USER: chashier
      POSTGRES_PASSWORD: chashier
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chashier"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    build:
      context: ../..
      dockerfile: infra/docker/api.Dockerfile
    env_file:
      - ../../apps/api/.env
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["pnpm","start:prod"]

  web:
    build:
      context: ../..
      dockerfile: infra/docker/web.Dockerfile
    env_file:
      - ../../apps/web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
